name = "csv-cleaner"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.routes]]
pattern = "csvcleaner.online/*"
zone_name = "csvcleaner.online"